Revert most of the changes from #1782
This is done manually as git apply with diff from d2edb0cae fails.
error: IBPSA/Fluid/Interfaces/PartialTwoPort.mo: patch does not apply